wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1651657667
    t:
      1:
      - 1
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 64
dataset_name:
  desc: null
  value: opensfm
delim:
  desc: null
  value: tab
drop_out:
  desc: null
  value: 0
embedding_dim:
  desc: null
  value: 0
hidden_dim:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
model_path:
  desc: null
  value: /home/michaellee/Desktop/Filming-GAN/fgan_practice/models
num_epochs:
  desc: null
  value: 500
num_layers:
  desc: null
  value: 1
obs_len:
  desc: null
  value: 8
pic_path:
  desc: null
  value: opensfm_test
pred_len:
  desc: null
  value: 8
skip:
  desc: null
  value: 1
