wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1647852287
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_norm:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
best_k:
  desc: null
  value: 1
bottleneck_dim:
  desc: null
  value: 32
checkpoint_every:
  desc: null
  value: 1000
checkpoint_name:
  desc: null
  value: checkpoint
checkpoint_start_from:
  desc: null
  value: null
clipping_threshold_d:
  desc: null
  value: 0
clipping_threshold_g:
  desc: null
  value: 0
d_learning_rate:
  desc: null
  value: 0.001
d_steps:
  desc: null
  value: 1
d_type:
  desc: null
  value: local
dataset_name:
  desc: null
  value: create
decoder_h_dim_g:
  desc: null
  value: 32
delim:
  desc: null
  value: tab
dropout:
  desc: null
  value: 0
embedding_dim:
  desc: null
  value: 16
encoder_h_dim_d:
  desc: null
  value: 64
encoder_h_dim_g:
  desc: null
  value: 32
g_learning_rate:
  desc: null
  value: 0.001
g_steps:
  desc: null
  value: 1
gpu_num:
  desc: null
  value: '0'
grid_size:
  desc: null
  value: 0
l2_loss_weight:
  desc: null
  value: 1
loader_num_workers:
  desc: null
  value: 1
mlp_dim:
  desc: null
  value: 64
neighborhood_size:
  desc: null
  value: 0.0
noise_dim:
  desc: null
  value:
  - 0
noise_mix_type:
  desc: null
  value: global
noise_type:
  desc: null
  value: gaussian
num_epochs:
  desc: null
  value: 200
num_iterations:
  desc: null
  value: 15000
num_layers:
  desc: null
  value: 1
num_samples_check:
  desc: null
  value: 5000
obs_len:
  desc: null
  value: 8
output_dir:
  desc: null
  value: /home/michaellee/Desktop/Github/sgan/scripts
pool_every_timestep:
  desc: null
  value: 0
pooling_type:
  desc: null
  value: null
pred_len:
  desc: null
  value: 8
print_every:
  desc: null
  value: 50
restore_from_checkpoint:
  desc: null
  value: 0
skip:
  desc: null
  value: 1
timing:
  desc: null
  value: 0
use_gpu:
  desc: null
  value: 1
